name: CivPvP
authors: [TeaJizzle, Maxopoly, TealNerd]
version: 1.0
main: com.gimmicknetwork.civpvpinventory.CivpvpInventory

depend: [NameLayer]

commands:
  inv:
    description: "Save/load inventories."
    usage: "Usage: /inv save/load <inventory> or /inv clear."
    permission: civpvpinventory.use
  duel:
    description: Requests to duel someone
    usage: "/duel <playername> or /duel team <playername>"
    permission: civpvpinventory.use
  accept:
    description: Accept the last duel request
    usage: "/accept"
    permission: civpvpinventory.use
  team:
    description: "Make and manage teams"
    usage: "Usage: /team create, /team invite <player>, or /team leave"
    permission: civpvpinventory.use
  elo:
    description: "Check your elo!"
    usage: "Usage: /elo"
    permission: civpvpinventory.use
  warp:
    description: "Add and remove warps for duels"
    usage: "/warp create/first/second"
    permission: civpvp.badmin
permissions:
  civpvpinventory.use:
    description: "use inventory saving/loading."
    default: true
  civpvp.badmin:
    description: "Admin crimes inc"
    default: op